### PR TITLE
DynamoDB.putConditional

### PR DESCRIPTION
**Pull request by beezee**
This PR introduces the ability to do conditional puts to dynamo.

It is a rough cut (no real syntax sugar, just one method on DynamoDB) but it gets the job done, and it's functionality I needed so I figured I'd offer it here.

Factors out Condition to work for both Condition and ExpectedAttributeValue and exposes DynamoDB.putConditional(tableName, attributes)(expectedAttributeValues)

If there's reasonable feedback I'm happy to spend a bit more effort polishing, or if it's sufficient as is I'm happy to see it merged.

Otherwise I'm using this as a library enhancement in the meantime.

### CODE REVIEW

**Comment by cluda** [comment]
+1 for this functionality

**Comment by mlovretovich** [comment]
+1

**Comment by seratch** [comment]
Would you mind rebasing this?

**Comment by beezee** [comment]
No problem, I'll try to find some time this weekend.

Let me know about the sbt version refs, I'm not sure what they are required for but they do prevent me from including the dependency straight from Github which I find very convenient.

**Comment by beezee** [comment]
Got a rebase, and re-focused the PR to only include putConditional.

I'm reopening from another branch, since this one is used as a github based dependency in a few of my projects.

**Pull request closed without merging**
