### PR TITLE
add billingMode support for dynamodb table

### PR DESCRIPTION
**Pull request by kimxogus**

### CODE REVIEW

**Comment by seratch** [comment]
The intention of the change looks good to me.

The CI build is failing due to some code style issues. It seems that scalariform is not applied yet. Please run `sbt test:compile` before pushing the change. https://travis-ci.org/seratch/AWScala/jobs/525245212

**Comment by kimxogus** [comment]
reformatted :)

**Comment by kimxogus** [comment]
also fixed test failure and added dynamodb local test

**Comment by seratch** [comment]
CI tests with openjdk are failing but the failures are not caused by your changes. Thank you for contribution!

**Comment by kimxogus** [comment]
👍 
Can you tell when this feature will be released? I'm using my own implementation in my application. Hope to use this feature with awscala

**Comment by seratch** [comment]
I'm working on the release now. I'll update you when it has been completed.

**Comment by seratch** [comment]
It's available now. Will be synced to Maven Central very soon. https://oss.sonatype.org/content/repositories/staging/com/github/seratch/awscala-dynamodb_2.12/0.8.2/

**Pull request merged**
