### PR TITLE
DynamoDB: simplify access to Items

### PR DESCRIPTION
**Pull request by larroy**
getItem and putItem without requiring a Table object which can be inconvenient

### CODE REVIEW

**Comment by seratch** [comment]
Allowing to just passing String tableName value instead of Table object is fine when get/putItem. But I'm not willing to accept other changes (removing Attribute class, Item constructor breaking change).

**Comment by larroy** [comment]
Do you want them separate? Or you don't want the other changes? I think it makes the lib simpler to use, just look at the test cases

**Comment by larroy** [comment]
the dynamo library needs work, as it is now, is not even usable in production. The query and scan operations are not even correct, they only work for small number of items. Plus the code that I removed was inefficient, having a linear access on a sequence of attributes. If you are not willing to merge these changes (and the future changes I'm doing) I will have no other option but to fork this library. I would prefer not doing that.

**Comment by seratch** [comment]
It's fine to have Map interface too like `lazy val attributesAsMap` (and hold it as the primary one internally). >having a linear access on a sequence of attributes

Read the README of this library. 

> AWScala enables Scala developers to easily work with Amazon Web Services in the Scala way. Though AWScala objects basically extend AWS SDK for Java APIs, you can use them with less stress on Scala REPL or sbt console.

If you need to deal with huge dataset on the JVM after fetching items from DynamoDB, you should create your own library which is optimized for your use cases.

**Comment by larroy** [comment]
Fair enough. Thanks for your attention.

**Pull request closed without merging**
