### PR TITLE
Custom Endpoint

### PR DESCRIPTION
**Pull request by tampler**
Added custom endpoint support. Updated credentials

### CODE REVIEW

**Comment by tampler** [comment]
Tested my implementation [here](https://github.com/Neurodyne/zio-aws/blob/master/src/test/scala/BaseSpec.scala)

**Comment by seratch** [comment]
Could you run compilation to run the code formatter before making git commits?

**Comment by tampler** [comment]
No, sorry. I'm not interested in this project anymore since I have got my own with V2 API: https://github.com/Neurodyne/zio-aws-s3

You can merge this as is to add a feature or close my PR

**Comment by seratch** [comment]
@tampler thanks for your reply! let me close this PR now.

**Pull request closed without merging**
